/**
 * AgendaMX — Business Templates
 * 12 plantillas preconfiguradas para onboarding instantáneo
 *
 * Cada template incluye:
 * - Servicios con precios sugeridos para México (MXN)
 * - Horarios típicos del giro
 * - Mensaje de bienvenida personalizado
 * - Categoría SEO
 * - Color de acento para el perfil público
 */

const TEMPLATES = [
  // ─────────────────────────────────────────────────────────────────
  {
    id: 'barberia',
    name: 'Barbería',
    emoji: '✂️',
    tagline: 'Cortes y afeitados profesionales',
    color: '#2D3748',
    accentColor: '#FF5C3A',
    seoCategory: 'Barbería y estética masculina',
    description: 'Para barberías, peluquerías masculinas y estéticas de caballero',
    welcomeMessage: '¡Bienvenido! Agenda tu corte o arreglo de barba fácil y rápido. Sin esperas, sin llamadas.',
    services: [
      { name: 'Corte clásico',        duration: 30, price: 150, icon: '✂️' },
      { name: 'Corte + Barba',        duration: 45, price: 220, icon: '🪒', popular: true },
      { name: 'Afeitado clásico',     duration: 30, price: 120, icon: '🧴' },
      { name: 'Barba + Perfilado',    duration: 25, price: 100, icon: '🧔' },
      { name: 'Corte niño',           duration: 20, price: 100, icon: '👦' },
      { name: 'Tinte / Mechas',       duration: 60, price: 300, icon: '🎨' },
      { name: 'Keratina exprés',      duration: 60, price: 380, icon: '💆' },
    ],
    hours: [
      { day: 1, opens: '09:00', closes: '20:00', isOpen: true  }, // Lunes
      { day: 2, opens: '09:00', closes: '20:00', isOpen: true  },
      { day: 3, opens: '09:00', closes: '20:00', isOpen: true  },
      { day: 4, opens: '09:00', closes: '20:00', isOpen: true  },
      { day: 5, opens: '09:00', closes: '20:00', isOpen: true  },
      { day: 6, opens: '09:00', closes: '18:00', isOpen: true  }, // Sábado
      { day: 0, opens: null,    closes: null,    isOpen: false }, // Domingo
    ],
  },

  // ─────────────────────────────────────────────────────────────────
  {
    id: 'salon-belleza',
    name: 'Salón de Belleza',
    emoji: '💅',
    tagline: 'Cabello, uñas y tratamientos',
    color: '#6B21A8',
    accentColor: '#D946EF',
    seoCategory: 'Salón de belleza y estética',
    description: 'Para salones de belleza, estéticas y centros de imagen femenina',
    welcomeMessage: '¡Hola! Agenda tu cita en segundos. Aquí encontrarás todos nuestros servicios de belleza disponibles.',
    services: [
      { name: 'Corte de cabello',     duration: 45, price: 200, icon: '✂️' },
      { name: 'Tinte completo',       duration: 120, price: 500, icon: '🎨', popular: true },
      { name: 'Mechas / Highlights',  duration: 150, price: 700, icon: '✨' },
      { name: 'Brushing / Peinado',   duration: 45, price: 180, icon: '💇' },
      { name: 'Uñas acrílicas',       duration: 90, price: 350, icon: '💅' },
      { name: 'Uñas gel / Semiperm',  duration: 60, price: 250, icon: '💅' },
      { name: 'Keratina',             duration: 180, price: 900, icon: '🌟' },
      { name: 'Tratamiento capilar',  duration: 60, price: 400, icon: '🧴' },
      { name: 'Maquillaje',           duration: 60, price: 350, icon: '💄' },
      { name: 'Depilación facial',    duration: 30, price: 150, icon: '🌿' },
    ],
    hours: [
      { day: 1, opens: '09:00', closes: '19:00', isOpen: true  },
      { day: 2, opens: '09:00', closes: '19:00', isOpen: true  },
      { day: 3, opens: '09:00', closes: '19:00', isOpen: true  },
      { day: 4, opens: '09:00', closes: '19:00', isOpen: true  },
      { day: 5, opens: '09:00', closes: '19:00', isOpen: true  },
      { day: 6, opens: '09:00', closes: '17:00', isOpen: true  },
      { day: 0, opens: null,    closes: null,    isOpen: false },
    ],
  },

  // ─────────────────────────────────────────────────────────────────
  {
    id: 'veterinaria',
    name: 'Veterinaria',
    emoji: '🐾',
    tagline: 'Salud y cuidado de tus mascotas',
    color: '#065F46',
    accentColor: '#10B981',
    seoCategory: 'Veterinaria y cuidado animal',
    description: 'Para clínicas veterinarias, consultorios y peluquerías caninas',
    welcomeMessage: '¡Bienvenido! Agenda la cita de tu mascota fácilmente. Cuidamos a tu peludo como si fuera nuestro.',
    services: [
      { name: 'Consulta general',     duration: 30, price: 300, icon: '🩺', popular: true },
      { name: 'Vacunación',           duration: 20, price: 250, icon: '💉' },
      { name: 'Baño + Corte canino',  duration: 90, price: 350, icon: '🐕' },
      { name: 'Desparasitación',      duration: 15, price: 200, icon: '💊' },
      { name: 'Limpieza dental',      duration: 60, price: 800, icon: '🦷' },
      { name: 'Microchip',            duration: 20, price: 400, icon: '📡' },
      { name: 'Cirugía menor',        duration: 60, price: 1500, icon: '🏥' },
      { name: 'Ultrasonido',          duration: 30, price: 600, icon: '📊' },
    ],
    hours: [
      { day: 1, opens: '09:00', closes: '19:00', isOpen: true  },
      { day: 2, opens: '09:00', closes: '19:00', isOpen: true  },
      { day: 3, opens: '09:00', closes: '19:00', isOpen: true  },
      { day: 4, opens: '09:00', closes: '19:00', isOpen: true  },
      { day: 5, opens: '09:00', closes: '19:00', isOpen: true  },
      { day: 6, opens: '09:00', closes: '14:00', isOpen: true  },
      { day: 0, opens: '10:00', closes: '13:00', isOpen: true  },
    ],
  },

  // ─────────────────────────────────────────────────────────────────
  {
    id: 'spa-masaje',
    name: 'Spa & Masajes',
    emoji: '🧖',
    tagline: 'Relajación y bienestar',
    color: '#7C3AED',
    accentColor: '#8B5CF6',
    seoCategory: 'Spa, masajes y bienestar',
    description: 'Para spas, centros de masaje, relajación y terapias corporales',
    welcomeMessage: 'Reserva tu momento de relajación. Te esperamos para darte la mejor experiencia de bienestar.',
    services: [
      { name: 'Masaje relajante 60 min',  duration: 60,  price: 500, icon: '💆', popular: true },
      { name: 'Masaje relajante 90 min',  duration: 90,  price: 700, icon: '💆' },
      { name: 'Masaje descontracturante', duration: 60,  price: 550, icon: '💪' },
      { name: 'Masaje de piedras',        duration: 75,  price: 700, icon: '🪨' },
      { name: 'Facial hidratante',        duration: 60,  price: 450, icon: '✨' },
      { name: 'Exfoliación corporal',     duration: 45,  price: 400, icon: '🌿' },
      { name: 'Terapia de aromaterapia',  duration: 60,  price: 500, icon: '🌸' },
      { name: 'Reflexología podal',       duration: 45,  price: 380, icon: '🦶' },
      { name: 'Envoltura corporal',       duration: 90,  price: 800, icon: '🫧' },
    ],
    hours: [
      { day: 1, opens: '10:00', closes: '20:00', isOpen: true  },
      { day: 2, opens: '10:00', closes: '20:00', isOpen: true  },
      { day: 3, opens: '10:00', closes: '20:00', isOpen: true  },
      { day: 4, opens: '10:00', closes: '20:00', isOpen: true  },
      { day: 5, opens: '10:00', closes: '20:00', isOpen: true  },
      { day: 6, opens: '10:00', closes: '18:00', isOpen: true  },
      { day: 0, opens: '11:00', closes: '16:00', isOpen: true  },
    ],
  },

  // ─────────────────────────────────────────────────────────────────
  {
    id: 'dentista',
    name: 'Dentista',
    emoji: '🦷',
    tagline: 'Salud y estética dental',
    color: '#0C4A6E',
    accentColor: '#0EA5E9',
    seoCategory: 'Odontología y salud dental',
    description: 'Para consultorios dentales, odontólogos y clínicas de estética dental',
    welcomeMessage: 'Agenda tu cita dental en línea. Sin llamadas, sin esperas. Tu salud bucal es nuestra prioridad.',
    services: [
      { name: 'Consulta + Revisión',      duration: 30, price: 300, icon: '🩺', popular: true },
      { name: 'Limpieza dental',          duration: 45, price: 500, icon: '✨' },
      { name: 'Extracción simple',        duration: 30, price: 600, icon: '🦷' },
      { name: 'Extracción muela juicio',  duration: 60, price: 1200, icon: '😬' },
      { name: 'Blanqueamiento dental',    duration: 60, price: 1500, icon: '⭐' },
      { name: 'Ortodoncia — consulta',    duration: 45, price: 400, icon: '😁' },
      { name: 'Resina / Obturación',      duration: 45, price: 800, icon: '🔧' },
      { name: 'Corona dental',            duration: 90, price: 3500, icon: '👑' },
      { name: 'Carilla de porcelana',     duration: 90, price: 4500, icon: '💎' },
    ],
    hours: [
      { day: 1, opens: '09:00', closes: '19:00', isOpen: true  },
      { day: 2, opens: '09:00', closes: '19:00', isOpen: true  },
      { day: 3, opens: '09:00', closes: '19:00', isOpen: true  },
      { day: 4, opens: '09:00', closes: '19:00', isOpen: true  },
      { day: 5, opens: '09:00', closes: '18:00', isOpen: true  },
      { day: 6, opens: '09:00', closes: '14:00', isOpen: true  },
      { day: 0, opens: null,    closes: null,    isOpen: false },
    ],
  },

  // ─────────────────────────────────────────────────────────────────
  {
    id: 'psicologo',
    name: 'Psicólogo',
    emoji: '🧠',
    tagline: 'Salud mental y bienestar emocional',
    color: '#1E3A5F',
    accentColor: '#6366F1',
    seoCategory: 'Psicología y salud mental',
    description: 'Para psicólogos, terapeutas, coaches y consejeros',
    welcomeMessage: 'Dar el primer paso es lo más valioso. Agenda tu consulta con total privacidad y confidencialidad.',
    services: [
      { name: 'Primera consulta',         duration: 60, price: 600, icon: '🤝', popular: true },
      { name: 'Consulta individual',      duration: 50, price: 700, icon: '💬' },
      { name: 'Terapia de pareja',        duration: 60, price: 900, icon: '💑' },
      { name: 'Terapia familiar',         duration: 75, price: 1000, icon: '👨‍👩‍👧' },
      { name: 'Consulta adolescentes',    duration: 50, price: 600, icon: '🧒' },
      { name: 'Evaluación psicológica',   duration: 90, price: 1200, icon: '📋' },
      { name: 'Sesión online',            duration: 50, price: 600, icon: '💻' },
    ],
    hours: [
      { day: 1, opens: '09:00', closes: '19:00', isOpen: true  },
      { day: 2, opens: '09:00', closes: '19:00', isOpen: true  },
      { day: 3, opens: '09:00', closes: '19:00', isOpen: true  },
      { day: 4, opens: '09:00', closes: '19:00', isOpen: true  },
      { day: 5, opens: '09:00', closes: '17:00', isOpen: true  },
      { day: 6, opens: null,    closes: null,    isOpen: false },
      { day: 0, opens: null,    closes: null,    isOpen: false },
    ],
  },

  // ─────────────────────────────────────────────────────────────────
  {
    id: 'nutriologo',
    name: 'Nutriólogo',
    emoji: '🥗',
    tagline: 'Nutrición y salud integral',
    color: '#14532D',
    accentColor: '#22C55E',
    seoCategory: 'Nutrición, dietética y salud',
    description: 'Para nutriólogos, dietistas, coaches de salud y bienestar',
    welcomeMessage: 'Tu salud empieza aquí. Agenda tu consulta nutricional y comienza tu transformación hoy.',
    services: [
      { name: 'Consulta inicial',         duration: 60, price: 500, icon: '📋', popular: true },
      { name: 'Consulta seguimiento',     duration: 30, price: 350, icon: '📊' },
      { name: 'Plan nutricional',         duration: 60, price: 700, icon: '🥗' },
      { name: 'Bioimpedancia',            duration: 20, price: 200, icon: '⚖️' },
      { name: 'Consulta online',          duration: 45, price: 400, icon: '💻' },
      { name: 'Taller grupal',            duration: 90, price: 300, icon: '👥' },
      { name: 'Coaching nutricional',     duration: 60, price: 600, icon: '🏆' },
    ],
    hours: [
      { day: 1, opens: '08:00', closes: '18:00', isOpen: true  },
      { day: 2, opens: '08:00', closes: '18:00', isOpen: true  },
      { day: 3, opens: '08:00', closes: '18:00', isOpen: true  },
      { day: 4, opens: '08:00', closes: '18:00', isOpen: true  },
      { day: 5, opens: '08:00', closes: '17:00', isOpen: true  },
      { day: 6, opens: '09:00', closes: '13:00', isOpen: true  },
      { day: 0, opens: null,    closes: null,    isOpen: false },
    ],
  },

  // ─────────────────────────────────────────────────────────────────
  {
    id: 'fotografo',
    name: 'Fotógrafo',
    emoji: '📸',
    tagline: 'Fotografía profesional',
    color: '#1C1917',
    accentColor: '#F59E0B',
    seoCategory: 'Fotografía y video profesional',
    description: 'Para fotógrafos, estudios fotográficos y videógrafos',
    welcomeMessage: '¡Hola! Agenda tu sesión fotográfica. Capturamos tus momentos más especiales con estilo único.',
    services: [
      { name: 'Sesión retrato 1 hr',     duration: 60,  price: 1200, icon: '🤳', popular: true },
      { name: 'Sesión familiar 2 hrs',   duration: 120, price: 2000, icon: '👨‍👩‍👧' },
      { name: 'Sesión XV años',          duration: 180, price: 4500, icon: '👸' },
      { name: 'Sesión de boda',          duration: 480, price: 12000, icon: '💍' },
      { name: 'Foto corporativa',        duration: 60,  price: 1500, icon: '👔' },
      { name: 'Sesión embarazo',         duration: 90,  price: 1800, icon: '🤰' },
      { name: 'Newborn / Bebé',          duration: 120, price: 2200, icon: '👶' },
      { name: 'Producto / Ecommerce',    duration: 120, price: 2000, icon: '📦' },
      { name: 'Video promocional',       duration: 240, price: 5000, icon: '🎬' },
    ],
    hours: [
      { day: 1, opens: '09:00', closes: '18:00', isOpen: true  },
      { day: 2, opens: '09:00', closes: '18:00', isOpen: true  },
      { day: 3, opens: '09:00', closes: '18:00', isOpen: true  },
      { day: 4, opens: '09:00', closes: '18:00', isOpen: true  },
      { day: 5, opens: '09:00', closes: '18:00', isOpen: true  },
      { day: 6, opens: '09:00', closes: '17:00', isOpen: true  },
      { day: 0, opens: '10:00', closes: '15:00', isOpen: true  },
    ],
  },

  // ─────────────────────────────────────────────────────────────────
  {
    id: 'tatuador',
    name: 'Tatuador',
    emoji: '🎨',
    tagline: 'Arte en tu piel',
    color: '#18181B',
    accentColor: '#A855F7',
    seoCategory: 'Tatuajes, piercing y arte corporal',
    description: 'Para estudios de tatuaje, tatuadores independientes y piercers',
    welcomeMessage: 'Tu próximo tatuaje empieza aquí. Agenda tu consulta o sesión con nuestros artistas.',
    services: [
      { name: 'Consulta / Diseño',       duration: 30,  price: 0,    icon: '✏️' },
      { name: 'Tatuaje pequeño',         duration: 60,  price: 800,  icon: '🎨', popular: true },
      { name: 'Tatuaje mediano',         duration: 120, price: 1800, icon: '🖋️' },
      { name: 'Tatuaje grande',          duration: 240, price: 3500, icon: '🖼️' },
      { name: 'Retoque / Touch-up',      duration: 60,  price: 400,  icon: '✨' },
      { name: 'Piercing básico',         duration: 20,  price: 300,  icon: '💎' },
      { name: 'Piercing cartílago',      duration: 20,  price: 400,  icon: '👂' },
      { name: 'Cover-up',                duration: 180, price: 2500, icon: '🔄' },
    ],
    hours: [
      { day: 1, opens: '12:00', closes: '20:00', isOpen: true  },
      { day: 2, opens: '12:00', closes: '20:00', isOpen: true  },
      { day: 3, opens: '12:00', closes: '20:00', isOpen: true  },
      { day: 4, opens: '12:00', closes: '20:00', isOpen: true  },
      { day: 5, opens: '12:00', closes: '21:00', isOpen: true  },
      { day: 6, opens: '11:00', closes: '20:00', isOpen: true  },
      { day: 0, opens: '12:00', closes: '18:00', isOpen: true  },
    ],
  },

  // ─────────────────────────────────────────────────────────────────
  {
    id: 'yoga-fitness',
    name: 'Yoga / Fitness',
    emoji: '🧘',
    tagline: 'Bienestar físico y mental',
    color: '#3F3F46',
    accentColor: '#F97316',
    seoCategory: 'Yoga, pilates, CrossFit y fitness',
    description: 'Para estudios de yoga, pilates, CrossFit, gimnasios y entrenadores personales',
    welcomeMessage: '¡Bienvenido a tu espacio de bienestar! Reserva tu lugar en clase antes de que se llene.',
    services: [
      { name: 'Clase grupal',            duration: 60, price: 150, icon: '🧘', popular: true },
      { name: 'Clase privada 1:1',       duration: 60, price: 450, icon: '🏋️' },
      { name: 'Paquete 4 clases',        duration: 60, price: 500, icon: '📦' },
      { name: 'Paquete 8 clases',        duration: 60, price: 900, icon: '📦' },
      { name: 'Evaluación física',       duration: 45, price: 300, icon: '📊' },
      { name: 'Entrenamiento funcional', duration: 60, price: 200, icon: '💪' },
      { name: 'Clase de meditación',     duration: 45, price: 120, icon: '🧠' },
      { name: 'Taller intensivo',        duration: 120, price: 350, icon: '⚡' },
    ],
    hours: [
      { day: 1, opens: '06:00', closes: '21:00', isOpen: true  },
      { day: 2, opens: '06:00', closes: '21:00', isOpen: true  },
      { day: 3, opens: '06:00', closes: '21:00', isOpen: true  },
      { day: 4, opens: '06:00', closes: '21:00', isOpen: true  },
      { day: 5, opens: '06:00', closes: '20:00', isOpen: true  },
      { day: 6, opens: '07:00', closes: '14:00', isOpen: true  },
      { day: 0, opens: '08:00', closes: '12:00', isOpen: true  },
    ],
  },

  // ─────────────────────────────────────────────────────────────────
  {
    id: 'tutor',
    name: 'Tutor / Maestro',
    emoji: '📚',
    tagline: 'Clases particulares y asesorías',
    color: '#1E3A5F',
    accentColor: '#3B82F6',
    seoCategory: 'Tutorías, clases particulares y educación',
    description: 'Para tutores, maestros particulares, academias y coaches educativos',
    welcomeMessage: '¡Hola! Agenda tu clase o asesoría fácilmente. Aprender nunca fue tan sencillo.',
    services: [
      { name: 'Clase 1 hora',            duration: 60,  price: 250, icon: '📖', popular: true },
      { name: 'Clase 90 minutos',        duration: 90,  price: 350, icon: '📝' },
      { name: 'Asesoría examen',         duration: 60,  price: 300, icon: '📋' },
      { name: 'Paquete 4 clases',        duration: 60,  price: 900, icon: '📦' },
      { name: 'Paquete 8 clases',        duration: 60,  price: 1700, icon: '📦' },
      { name: 'Clase online',            duration: 60,  price: 200, icon: '💻' },
      { name: 'Taller grupal',           duration: 90,  price: 150, icon: '👥' },
    ],
    hours: [
      { day: 1, opens: '07:00', closes: '21:00', isOpen: true  },
      { day: 2, opens: '07:00', closes: '21:00', isOpen: true  },
      { day: 3, opens: '07:00', closes: '21:00', isOpen: true  },
      { day: 4, opens: '07:00', closes: '21:00', isOpen: true  },
      { day: 5, opens: '07:00', closes: '20:00', isOpen: true  },
      { day: 6, opens: '09:00', closes: '15:00', isOpen: true  },
      { day: 0, opens: null,    closes: null,    isOpen: false },
    ],
  },

  // ─────────────────────────────────────────────────────────────────
  {
    id: 'medico',
    name: 'Médico / Clínica',
    emoji: '🩺',
    tagline: 'Consultas y servicios médicos',
    color: '#0C4A6E',
    accentColor: '#06B6D4',
    seoCategory: 'Medicina general y especialidades',
    description: 'Para médicos generales, especialistas, clínicas y consultorios médicos',
    welcomeMessage: 'Tu salud es nuestra prioridad. Agenda tu consulta médica en línea de forma rápida y segura.',
    services: [
      { name: 'Consulta general',        duration: 30, price: 400, icon: '🩺', popular: true },
      { name: 'Consulta urgencia',       duration: 30, price: 500, icon: '🚑' },
      { name: 'Revisión de resultados',  duration: 20, price: 300, icon: '📊' },
      { name: 'Aplicación de medicamento', duration: 15, price: 150, icon: '💉' },
      { name: 'Curación / Vendaje',      duration: 20, price: 200, icon: '🩹' },
      { name: 'Certificado médico',      duration: 20, price: 250, icon: '📋' },
      { name: 'Consulta online',         duration: 30, price: 350, icon: '💻' },
    ],
    hours: [
      { day: 1, opens: '08:00', closes: '18:00', isOpen: true  },
      { day: 2, opens: '08:00', closes: '18:00', isOpen: true  },
      { day: 3, opens: '08:00', closes: '18:00', isOpen: true  },
      { day: 4, opens: '08:00', closes: '18:00', isOpen: true  },
      { day: 5, opens: '08:00', closes: '17:00', isOpen: true  },
      { day: 6, opens: '09:00', closes: '13:00', isOpen: true  },
      { day: 0, opens: null,    closes: null,    isOpen: false },
    ],
  },
]

module.exports = TEMPLATES
